# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/amathael/fdupes

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/amathael/fdupes

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amathael/fdupes/CMakeFiles /home/amathael/fdupes/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/amathael/fdupes/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fdupes

# Build rule for target.
fdupes: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fdupes
.PHONY : fdupes

# fast build rule for target.
fdupes/fast:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/build
.PHONY : fdupes/fast

#=============================================================================
# Target rules for targets named fdupes_automoc

# Build rule for target.
fdupes_automoc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fdupes_automoc
.PHONY : fdupes_automoc

# fast build rule for target.
fdupes_automoc/fast:
	$(MAKE) -f CMakeFiles/fdupes_automoc.dir/build.make CMakeFiles/fdupes_automoc.dir/build
.PHONY : fdupes_automoc/fast

duplicates_scanner.o: duplicates_scanner.cpp.o

.PHONY : duplicates_scanner.o

# target to build an object file
duplicates_scanner.cpp.o:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/duplicates_scanner.cpp.o
.PHONY : duplicates_scanner.cpp.o

duplicates_scanner.i: duplicates_scanner.cpp.i

.PHONY : duplicates_scanner.i

# target to preprocess a source file
duplicates_scanner.cpp.i:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/duplicates_scanner.cpp.i
.PHONY : duplicates_scanner.cpp.i

duplicates_scanner.s: duplicates_scanner.cpp.s

.PHONY : duplicates_scanner.s

# target to generate assembly for a file
duplicates_scanner.cpp.s:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/duplicates_scanner.cpp.s
.PHONY : duplicates_scanner.cpp.s

fdupes_automoc.o: fdupes_automoc.cpp.o

.PHONY : fdupes_automoc.o

# target to build an object file
fdupes_automoc.cpp.o:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/fdupes_automoc.cpp.o
.PHONY : fdupes_automoc.cpp.o

fdupes_automoc.i: fdupes_automoc.cpp.i

.PHONY : fdupes_automoc.i

# target to preprocess a source file
fdupes_automoc.cpp.i:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/fdupes_automoc.cpp.i
.PHONY : fdupes_automoc.cpp.i

fdupes_automoc.s: fdupes_automoc.cpp.s

.PHONY : fdupes_automoc.s

# target to generate assembly for a file
fdupes_automoc.cpp.s:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/fdupes_automoc.cpp.s
.PHONY : fdupes_automoc.cpp.s

file_counter.o: file_counter.cpp.o

.PHONY : file_counter.o

# target to build an object file
file_counter.cpp.o:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/file_counter.cpp.o
.PHONY : file_counter.cpp.o

file_counter.i: file_counter.cpp.i

.PHONY : file_counter.i

# target to preprocess a source file
file_counter.cpp.i:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/file_counter.cpp.i
.PHONY : file_counter.cpp.i

file_counter.s: file_counter.cpp.s

.PHONY : file_counter.s

# target to generate assembly for a file
file_counter.cpp.s:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/file_counter.cpp.s
.PHONY : file_counter.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/fdupes.dir/build.make CMakeFiles/fdupes.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... fdupes"
	@echo "... fdupes_automoc"
	@echo "... duplicates_scanner.o"
	@echo "... duplicates_scanner.i"
	@echo "... duplicates_scanner.s"
	@echo "... fdupes_automoc.o"
	@echo "... fdupes_automoc.i"
	@echo "... fdupes_automoc.s"
	@echo "... file_counter.o"
	@echo "... file_counter.i"
	@echo "... file_counter.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

